//! from linux/include/uapi/asm-generic/unistd.h

define_syscall_ids!{
    SYSCALL_IO_SETUP = 0,
    SYSCALL_IO_DESTROY = 1,
    SYSCALL_IO_SUBMIT = 2,
    SYSCALL_IO_CANCEL = 3,
    SYSCALL_IO_GETEVENTS = 4,

/* fs/xattr.c */
    SYSCALL_SETXATTR = 5,
    SYSCALL_LSETXATTR = 6,
    SYSCALL_FSETXATTR = 7,
    SYSCALL_GETXATTR = 8,
    SYSCALL_LGETXATTR = 9,
    SYSCALL_FGETXATTR = 10,
    SYSCALL_LISTXATTR = 11,
    SYSCALL_LLISTXATTR = 12,
    SYSCALL_FLISTXATTR = 13,
    SYSCALL_REMOVEXATTR = 14,
    SYSCALL_LREMOVEXATTR = 15,
    SYSCALL_FREMOVEXATTR = 16,

/* fs/dcache.c */
    SYSCALL_GETCWD = 17,

/* fs/cookies.c */
    SYSCALL_LOOKUP_DCOOKIE = 18,

/* fs/eventfd.c */
    SYSCALL_EVENTFD2 = 19,

/* fs/eventpoll.c */
    SYSCALL_EPOLL_CREATE1 = 20,
    SYSCALL_EPOLL_CTL = 21,
    SYSCALL_EPOLL_PWAIT = 22,

/* fs/fcntl.c */
    SYSCALL_DUP = 23,
    SYSCALL_DUP3 = 24,
    SYSCALL_FCNTL = 25,

/* fs/inotify_user.c */
    SYSCALL_INOTIFY_INIT1 = 26,
    SYSCALL_INOTIFY_ADD_WATCH = 27,
    SYSCALL_INOTIFY_RM_WATCH = 28,

/* fs/ioctl.c */
    SYSCALL_IOCTL = 29,

/* fs/ioprio.c */
    SYSCALL_IOPRIO_SET = 30,
    SYSCALL_IOPRIO_GET = 31,

/* fs/locks.c */
    SYSCALL_FLOCK = 32,

/* fs/namei.c */
    SYSCALL_MKNODAT = 33,
    SYSCALL_MKDIRAT = 34,
    SYSCALL_UNLINKAT = 35,
    SYSCALL_SYMLINKAT = 36,
    SYSCALL_LINKAT = 37,
    SYSCALL_RENAMEAT = 38,

/* fs/namespace.c */
    SYSCALL_UMOUNT2 = 39,
    SYSCALL_MOUNT = 40,
    SYSCALL_PIVOT_ROOT = 41,

/* fs/nfsctl.c */
    SYSCALL_NFSSERVCTL = 42,

/* fs/open.c */
    SYSCALL_STATFS = 43,
    SYSCALL_FSTATFS = 44,
    SYSCALL_TRUNCATE = 45,
    SYSCALL_FTRUNCATE = 46,

    SYSCALL_FALLOCATE = 47,
    SYSCALL_FACCESSAT = 48,
    SYSCALL_CHDIR = 49,
    SYSCALL_FCHDIR = 50,
    SYSCALL_CHROOT = 51,
    SYSCALL_FCHMOD = 52,
    SYSCALL_FCHMODAT = 53,
    SYSCALL_FCHOWNAT = 54,
    SYSCALL_FCHOWN = 55,
    SYSCALL_OPENAT = 56,
    SYSCALL_CLOSE = 57,
    SYSCALL_VHANGUP = 58,

/* fs/pipe.c */
    SYSCALL_PIPE2 = 59,

/* fs/quota.c */
    SYSCALL_QUOTACTL = 60,

/* fs/readdir.c */
    SYSCALL_GETDENTS64 = 61,

/* fs/read_write.c */
    SYSCALL_LSEEK = 62,
    SYSCALL_READ = 63,
    SYSCALL_WRITE = 64,
    SYSCALL_READV = 65,
    SYSCALL_WRITEV = 66,
    SYSCALL_PREAD64 = 67,
    SYSCALL_PWRITE64 = 68,
    SYSCALL_PREADV = 69,
    SYSCALL_PWRITEV = 70,

/* fs/sendfile.c */
    SYSCALL_SENDFILE = 71,

/* fs/select.c */
    SYSCALL_PSELECT6 = 72,
    SYSCALL_PPOLL = 73,

/* fs/signalfd.c */
    SYSCALL_SIGNALFD4 = 74,

/* fs/splice.c */
    SYSCALL_VMSPLICE = 75,
    SYSCALL_SPLICE = 76,
    SYSCALL_TEE = 77,

/* fs/stat.c */
    SYSCALL_READLINKAT = 78,
    SYSCALL_FSTATAT = 79,
    SYSCALL_FSTAT = 80,

/* fs/sync.c */
    SYSCALL_SYNC = 81,
    SYSCALL_FSYNC = 82,
    SYSCALL_FDATASYNC = 83,
    SYSCALL_SYNC_FILE_RANGE = 84,

/* fs/timerfd.c */
    SYSCALL_TIMERFD_CREATE = 85,
    SYSCALL_TIMERFD_SETTIME = 86,
    SYSCALL_TIMERFD_GETTIME = 87,

/* fs/utimes.c */
    SYSCALL_UTIMENSAT = 88,

/* kernel/acct.c */
    SYSCALL_ACCT = 89,

/* kernel/capability.c */
    SYSCALL_CAPGET = 90,
    SYSCALL_CAPSET = 91,

/* kernel/exec_domain.c */
    SYSCALL_PERSONALITY = 92,

/* kernel/exit.c */
    SYSCALL_EXIT = 93,
    SYSCALL_EXIT_GROUP = 94,
    SYSCALL_WAITID = 95,

/* kernel/fork.c */
    SYSCALL_SET_TID_ADDRESS = 96,
    SYSCALL_UNSHARE = 97,

/* kernel/futex.c */
    SYSCALL_FUTEX = 98,
    SYSCALL_SET_ROBUST_LIST = 99,
    SYSCALL_GET_ROBUST_LIST = 100,

/* kernel/hrtimer.c */
    SYSCALL_NANOSLEEP = 101,

/* kernel/itimer.c */
    SYSCALL_GETITIMER = 102,
    SYSCALL_SETITIMER = 103,

/* kernel/kexec.c */
    SYSCALL_KEXEC_LOAD = 104,

/* kernel/module.c */
    SYSCALL_INIT_MODULE = 105,
    SYSCALL_DELETE_MODULE = 106,

/* kernel/posix-timers.c */
    SYSCALL_TIMER_CREATE = 107,
    SYSCALL_TIMER_GETTIME = 108,
    SYSCALL_TIMER_GETOVERRUN = 109,
    SYSCALL_TIMER_SETTIME = 110,
    SYSCALL_TIMER_DELETE = 111,
    SYSCALL_CLOCK_SETTIME = 112,
    SYSCALL_CLOCK_GETTIME = 113,
    SYSCALL_CLOCK_GETRES = 114,
    SYSCALL_CLOCK_NANOSLEEP = 115,

/* kernel/printk.c */
    SYSCALL_SYSLOG = 116,

/* kernel/ptrace.c */
    SYSCALL_PTRACE = 117,

/* kernel/sched/core.c */
    SYSCALL_SCHED_SETPARAM = 118,
    SYSCALL_SCHED_SETSCHEDULER = 119,
    SYSCALL_SCHED_GETSCHEDULER = 120,
    SYSCALL_SCHED_GETPARAM = 121,
    SYSCALL_SCHED_SETAFFINITY = 122,
    SYSCALL_SCHED_GETAFFINITY = 123,
    SYSCALL_SCHED_YIELD = 124,
    SYSCALL_SCHED_GET_PRIORITY_MAX = 125,
    SYSCALL_SCHED_GET_PRIORITY_MIN = 126,
    SYSCALL_SCHED_RR_GET_INTERVAL = 127,

/* kernel/signal.c */
    SYSCALL_RESTART_SYSCALL = 128,
    SYSCALL_KILL = 129,
    SYSCALL_TKILL = 130,
    SYSCALL_TGKILL = 131,
    SYSCALL_SIGALTSTACK = 132,
    SYSCALL_RT_SIGSUSPEND = 133,
    SYSCALL_RT_SIGACTION = 134,
    SYSCALL_RT_SIGPROCMASK = 135,
    SYSCALL_RT_SIGPENDING = 136,
    SYSCALL_RT_SIGTIMEDWAIT = 137,
    SYSCALL_RT_SIGQUEUEINFO = 138,
    SYSCALL_RT_SIGRETURN = 139,

/* kernel/sys.c */
    SYSCALL_SETPRIORITY = 140,
    SYSCALL_GETPRIORITY = 141,
    SYSCALL_REBOOT = 142,
    SYSCALL_SETREGID = 143,
    SYSCALL_SETGID = 144,
    SYSCALL_SETREUID = 145,
    SYSCALL_SETUID = 146,
    SYSCALL_SETRESUID = 147,
    SYSCALL_GETRESUID = 148,
    SYSCALL_SETRESGID = 149,
    SYSCALL_GETRESGID = 150,
    SYSCALL_SETFSUID = 151,
    SYSCALL_SETFSGID = 152,
    SYSCALL_TIMES = 153,
    SYSCALL_SETPGID = 154,
    SYSCALL_GETPGID = 155,
    SYSCALL_GETSID = 156,
    SYSCALL_SETSID = 157,
    SYSCALL_GETGROUPS = 158,
    SYSCALL_SETGROUPS = 159,
    SYSCALL_UNAME = 160,
    SYSCALL_SETHOSTNAME = 161,
    SYSCALL_SETDOMAINNAME = 162,

/* getrlimit and setrlimit are superseded with prlimit64 */
    SYSCALL_GETRLIMIT = 163,
    SYSCALL_SETRLIMIT = 164,

    SYSCALL_GETRUSAGE = 165,
    SYSCALL_UMASK = 166,
    SYSCALL_PRCTL = 167,
    SYSCALL_GETCPU = 168,

/* kernel/time.c */
    SYSCALL_GETTIMEOFDAY = 169,
    SYSCALL_SETTIMEOFDAY = 170,
    SYSCALL_ADJTIMEX = 171,

/* kernel/sys.c */
    SYSCALL_GETPID = 172,
    SYSCALL_GETPPID = 173,
    SYSCALL_GETUID = 174,
    SYSCALL_GETEUID = 175,
    SYSCALL_GETGID = 176,
    SYSCALL_GETEGID = 177,
    SYSCALL_GETTID = 178,
    SYSCALL_SYSINFO = 179,

/* ipc/mqueue.c */
    SYSCALL_MQ_OPEN = 180,
    SYSCALL_MQ_UNLINK = 181,
    SYSCALL_MQ_TIMEDSEND = 182,
    SYSCALL_MQ_TIMEDRECEIVE = 183,
    SYSCALL_MQ_NOTIFY = 184,
    SYSCALL_MQ_GETSETATTR = 185,

/* ipc/msg.c */
    SYSCALL_MSGGET = 186,
    SYSCALL_MSGCTL = 187,
    SYSCALL_MSGRCV = 188,
    SYSCALL_MSGSND = 189,

/* ipc/sem.c */
    SYSCALL_SEMGET = 190,
    SYSCALL_SEMCTL = 191,
    SYSCALL_SEMTIMEDOP = 192,
    SYSCALL_SEMOP = 193,

/* ipc/shm.c */
    SYSCALL_SHMGET = 194,
    SYSCALL_SHMCTL = 195,
    SYSCALL_SHMAT = 196,
    SYSCALL_SHMDT = 197,

/* net/socket.c */
    SYSCALL_SOCKET = 198,
    SYSCALL_SOCKETPAIR = 199,
    SYSCALL_BIND = 200,
    SYSCALL_LISTEN = 201,
    SYSCALL_ACCEPT = 202,
    SYSCALL_CONNECT = 203,
    SYSCALL_GETSOCKNAME = 204,
    SYSCALL_GETPEERNAME = 205,
    SYSCALL_SENDTO = 206,
    SYSCALL_RECVFROM = 207,
    SYSCALL_SETSOCKOPT = 208,
    SYSCALL_GETSOCKOPT = 209,
    SYSCALL_SHUTDOWN = 210,
    SYSCALL_SENDMSG = 211,
    SYSCALL_RECVMSG = 212,

/* mm/filemap.c */
    SYSCALL_READAHEAD = 213,

/* mm/nommu.c, also with MMU */
    SYSCALL_BRK = 214,
    SYSCALL_MUNMAP = 215,
    SYSCALL_MREMAP = 216,

/* security/keys/keyctl.c */
    SYSCALL_ADD_KEY = 217,
    SYSCALL_REQUEST_KEY = 218,
    SYSCALL_KEYCTL = 219,

/* arch/example/kernel/sys_example.c */
    SYSCALL_CLONE = 220,
    SYSCALL_EXECVE = 221,

    SYSCALL_MMAP = 222,
/* mm/fadvise.c */
    SYSCALL_FADVISE64 = 223,

/* mm/, CONFIG_MMU only */
    SYSCALL_SWAPON = 224,
    SYSCALL_SWAPOFF = 225,
    SYSCALL_MPROTECT = 226,
    SYSCALL_MSYNC = 227,
    SYSCALL_MLOCK = 228,
    SYSCALL_MUNLOCK = 229,
    SYSCALL_MLOCKALL = 230,
    SYSCALL_MUNLOCKALL = 231,
    SYSCALL_MINCORE = 232,
    SYSCALL_MADVISE = 233,
    SYSCALL_REMAP_FILE_PAGES = 234,
    SYSCALL_MBIND = 235,
    SYSCALL_GET_MEMPOLICY = 236,
    SYSCALL_SET_MEMPOLICY = 237,
    SYSCALL_MIGRATE_PAGES = 238,
    SYSCALL_MOVE_PAGES = 239,

    SYSCALL_RT_TGSIGQUEUEINFO = 240,
    SYSCALL_PERF_EVENT_OPEN = 241,
    SYSCALL_ACCEPT4 = 242,
    SYSCALL_RECVMMSG = 243,

/*
 * Architectures may provide up to 16 syscalls of their own
 * starting with this value.
 */
    SYSCALL_ARCH_SPECIFIC_SYSCALL = 244,

    SYSCALL_WAIT4 = 260,
    SYSCALL_PRLIMIT64 = 261,
    SYSCALL_FANOTIFY_INIT = 262,
    SYSCALL_FANOTIFY_MARK = 263,
    SYSCALL_NAME_TO_HANDLE_AT         = 264,
    SYSCALL_OPEN_BY_HANDLE_AT         = 265,
    SYSCALL_CLOCK_ADJTIME = 266,
    SYSCALL_SYNCFS = 267,
    SYSCALL_SETNS = 268,
    SYSCALL_SENDMMSG = 269,
    SYSCALL_PROCESS_VM_READV = 270,
    SYSCALL_PROCESS_VM_WRITEV = 271,
    SYSCALL_KCMP = 272,
    SYSCALL_FINIT_MODULE = 273,
    SYSCALL_SCHED_SETATTR = 274,
    SYSCALL_SCHED_GETATTR = 275,
    SYSCALL_RENAMEAT2 = 276,
    SYSCALL_SECCOMP = 277,
    SYSCALL_GETRANDOM = 278,
    SYSCALL_MEMFD_CREATE = 279,
    SYSCALL_BPF = 280,
    SYSCALL_EXECVEAT = 281,
    SYSCALL_USERFAULTFD = 282,
    SYSCALL_MEMBARRIER = 283,
    SYSCALL_MLOCK2 = 284,
    SYSCALL_COPY_FILE_RANGE = 285,
    SYSCALL_PREADV2 = 286,
    SYSCALL_PWRITEV2 = 287,
    SYSCALL_PKEY_MPROTECT = 288,
    SYSCALL_PKEY_ALLOC = 289,
    SYSCALL_PKEY_FREE = 290,
    SYSCALL_STATX = 291,
    SYSCALL_IO_PGETEVENTS = 292,
    SYSCALL_RSEQ = 293,
    SYSCALL_KEXEC_FILE_LOAD = 294,
/* 295 through 402 are unassigned to sync up with generic numbers, don't use */
    SYSCALL_CLOCK_GETTIME64 = 403,
    SYSCALL_CLOCK_SETTIME64 = 404,
    SYSCALL_CLOCK_ADJTIME64 = 405,
    SYSCALL_CLOCK_GETRES_TIME64 = 406,
    SYSCALL_CLOCK_NANOSLEEP_TIME64 = 407,
    SYSCALL_TIMER_GETTIME64 = 408,
    SYSCALL_TIMER_SETTIME64 = 409,
    SYSCALL_TIMERFD_GETTIME64 = 410,
    SYSCALL_TIMERFD_SETTIME64 = 411,
    SYSCALL_UTIMENSAT_TIME64 = 412,
    SYSCALL_PSELECT6_TIME64 = 413,
    SYSCALL_PPOLL_TIME64 = 414,
    SYSCALL_IO_PGETEVENTS_TIME64 = 416,
    SYSCALL_RECVMMSG_TIME64 = 417,
    SYSCALL_MQ_TIMEDSEND_TIME64 = 418,
    SYSCALL_MQ_TIMEDRECEIVE_TIME64 = 419,
    SYSCALL_SEMTIMEDOP_TIME64 = 420,
    SYSCALL_RT_SIGTIMEDWAIT_TIME64 = 421,
    SYSCALL_FUTEX_TIME64 = 422,
    SYSCALL_SCHED_RR_GET_INTERVAL_TIME64 = 423,

    SYSCALL_PIDFD_SEND_SIGNAL = 424,
    SYSCALL_IO_URING_SETUP = 425,
    SYSCALL_IO_URING_ENTER = 426,
    SYSCALL_IO_URING_REGISTER = 427,
    SYSCALL_OPEN_TREE = 428,
    SYSCALL_MOVE_MOUNT = 429,
    SYSCALL_FSOPEN = 430,
    SYSCALL_FSCONFIG = 431,
    SYSCALL_FSMOUNT = 432,
    SYSCALL_FSPICK = 433,
    SYSCALL_PIDFD_OPEN = 434,
    SYSCALL_CLONE3 = 435,
    SYSCALL_CLOSE_RANGE = 436,

    SYSCALL_OPENAT2 = 437,
    SYSCALL_PIDFD_GETFD = 438,
    SYSCALL_FACCESSAT2 = 439,
    SYSCALL_PROCESS_MADVISE = 440,
    SYSCALL_EPOLL_PWAIT2 = 441,
    SYSCALL_MOUNT_SETATTR = 442,
    SYSCALL_QUOTACTL_FD = 443,

    SYSCALL_LANDLOCK_CREATE_RULESET = 444,
    SYSCALL_LANDLOCK_ADD_RULE = 445,
    SYSCALL_LANDLOCK_RESTRICT_SELF = 446,

    SYSCALL_MEMFD_SECRET = 447,
    SYSCALL_PROCESS_MRELEASE = 448,

    SYSCALL_FUTEX_WAITV = 449,

    SYSCALL_SET_MEMPOLICY_HOME_NODE = 450,

    SYSCALL_SYSCALLS = 451
}
